server:
  port: 8090


spring:
    datasource:
        name: mysql_mytest
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
          username: root
          password: mypass


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.crud.onestep.model

thymeleaf:
  suffix: .html
  cache: false
